### ISSUE TITLE
Cannot resolve DNS hostname of registry from docker-registry-browser

### ISSUE THREAD

**Issue by ghost** [klausmeyer/docker-registry-browser#18] opened 2017-12-21 00:29 UTC
I'm having to use hard-coded IP address of my docker registry as the FQDN seems to cause issues with this container. 

Registry URL: https://registry.myhost.local:5001

When browsing the docker-registry-browser **the front page loads fine and lists all my images**, however **upon clicking the image, the page errors, and the following is shown in the logs**:

```
F, [2017-12-21T00:16:21.047264 #7] FATAL -- : [2f75f589-a26a-4ae1-87b0-85442b7b0d88]
F, [2017-12-21T00:16:21.047315 #7] FATAL -- : [2f75f589-a26a-4ae1-87b0-85442b7b0d88] Faraday::ConnectionFailed (Failed to open TCP connection to registry.myhost.local:5001 (getaddrinfo: Name does not resolve)):
F, [2017-12-21T00:16:21.047356 #7] FATAL -- : [2f75f589-a26a-4ae1-87b0-85442b7b0d88]
F, [2017-12-21T00:16:21.047483 #7] FATAL -- : [2f75f589-a26a-4ae1-87b0-85442b7b0d88] app/models/repository.rb:7:in `list'
```

- The docker host can resolve the address fine from command line. 
- The container itself must be able to resolve since the initial page loaded my images fine, it's only after clicking on an image name to browse it is when it fails. 
- **From WITHIN the container, a ping is successful:**  
```
/app # ping registry.myhost.local
PING registry.myhost.local (10.1.5.22): 56 data bytes
64 bytes from 10.1.5.22: seq=0 ttl=64 time=0.049 ms
```

The error on the web page just states: 
_We're sorry, but something went wrong.
If you are the application owner check the logs for more information._

**Comment by klausmeyer** [comment] 2017-12-21 06:21
Hi @mdebord1,

thanks for reporting that issue.

Since I'm not able to reproduce the issue currently (tried with adding your FQDN to my `/etc/hosts` - but of course that's not the same) I'd need some more information from you:

Would it be possible that you send me the output of `docker inspect` for the registry-browser container without the hardcoded IP? Also it would be good to know if the `registry.myhost.local` is resolved by an actual DNS server in your network or if you're relying on [mDNS](https://en.wikipedia.org/wiki/.local) there.

I also had a look at the implementation of listing images and showing the details of a single one and they're using both the exact same HTTP client so it's really odd that you're experiencing that issue.

Thank you

Klaus

**Comment by mdebord1** [comment] 2017-12-21 17:47
Hi - Thanks for helping investigate. 

- Yes it's DNS, a Bind9 DNS server on our internal network. 
- Here is the docker inspect on the container USING the hostname: https://pastebin.com/7nf6gj5c
- Here is the resolv.conf of the container: 
```root@root@docker10z:/dockerdata/Docker-Compose/registry_browser_dns# docker exec -it -u root registry_browser_dns cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.10.50.254
search myhost.local```

I did find something odd - when running nslookup from the container, it spits out "can't resolve '(null)' but then it ends up resolving. 

```
root@docker10z:/dockerdata/Docker-Compose/registry_browser_dns# docker exec -it -u root registry_browser_dns sh
/app # nslookup registry.myhost.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      registry.myhost.local
Address 1: 10.1.5.22 registry.myhost.local
/app # nslookup registry
nslookup: can't resolve '(null)': Name does not resolve

Name:      registry
Address 1: 10.1.5.22 registry
/app # ping registry.myhost.local
PING registry.myhost.local (10.1.5.22): 56 data bytes
64 bytes from 10.1.5.22: seq=0 ttl=64 time=0.043 ms
```

**Comment by klausmeyer** [comment] 2017-12-21 18:11
Thanks for the Pastebin 😀

I can't see anything special in that `docker inspect` output - it looks totally fine so it should not be a configuration issue on that level I think.

> I did find something odd - when running nslookup from the container, it spits out "can't resolve '(null)' but then it ends up resolving.

That's ok. As far as I know the `nslookup` (at least the version from busybox in alpine) just tries to do a reverse lookup for the IP of your nameserver which to show the FQDN. I have the same warning in an blank alpine container:

```
[ meyer at km-macbookair in ~ ] ruby-2.4.2
» docker run -it alpine sh
/ # nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      google.com
Address 1: 216.58.207.174 muc11s04-in-f14.1e100.net
Address 2: 2a00:1450:4016:807::200e muc11s04-in-x0e.1e100.net
```

Currently I don't have any clue what could be the issue.
Is it always the case that the list of loads and the detail page raises this error or do you maybe also get the same error if you refresh the list in a faster sequence?

**Comment by mdebord1** [comment] 2017-12-21 18:24
Yea I'm baffled myself. 

**Here are the application logs after loading the front page, where the list of images loads successfully. In response to your question, I cannot seem to get this to fail. Even after multiple refreshes** 

```
I, [2017-12-21T18:15:41.232544 #7]  INFO -- : [481b85ad-369c-4afd-9e41-6965cc83496a] Started GET "/" for 10.10.60.254 at 2017-12-21 18:15:41 +0000
I, [2017-12-21T18:15:41.233193 #7]  INFO -- : [481b85ad-369c-4afd-9e41-6965cc83496a] Processing by RepositoriesController#index as HTML
I, [2017-12-21T18:15:41.234011 #7]  INFO -- : get https://registry.myhost.local:5001/v2/_catalog?n=100
D, [2017-12-21T18:15:41.234071 #7] DEBUG -- request: User-Agent: "Faraday v0.11.0"
I, [2017-12-21T18:15:41.261065 #7]  INFO -- Status: 200
D, [2017-12-21T18:15:41.261145 #7] DEBUG -- response: content-type: "application/json; charset=utf-8"
docker-distribution-api-version: "registry/2.0"
x-content-type-options: "nosniff"
date: "Thu, 21 Dec 2017 18:15:41 GMT"
content-length: "210"
connection: "close"
I, [2017-12-21T18:15:41.261760 #7]  INFO -- : [481b85ad-369c-4afd-9e41-6965cc83496a]   Rendering repositories/index.html.erb within layouts/application
I, [2017-12-21T18:15:41.263564 #7]  INFO -- : [481b85ad-369c-4afd-9e41-6965cc83496a]   Rendered repositories/index.html.erb within layouts/application (1.7ms)
I, [2017-12-21T18:15:41.264192 #7]  INFO -- : [481b85ad-369c-4afd-9e41-6965cc83496a]   Rendered application/_flash.html.erb (0.1ms)
I, [2017-12-21T18:15:41.264461 #7]  INFO -- : [481b85ad-369c-4afd-9e41-6965cc83496a] Completed 200 OK in 31ms (Views: 3.0ms)
```

I'm going to destroy everything and start from scratch and see what I can come up with.

**Comment by mdebord1** [comment] 2017-12-21 18:29
Ok after destroying and rebuilding the container fully from scratch I am now able to get the front page to fail with the same error. Upon refreshing several times, it will load, then it will fail again sporadically.  

Very sporadic, might have something to do with my network but everything else resolves from DNS and it resolves at the command line without issue. I'm going to just keep using the hardcoded IP for now as a workaround.

**Comment by klausmeyer** [comment] 2017-12-21 18:36
Thanks for the feedback.

I agree - it sounds very much like something in your network or maybe on the docker-host itself.
How up-to-date is your docker version?

**Comment by jmmen1** [comment] 2019-01-16 23:04
Can we re-open this issue?

I was browsing my registry and noticed some tags were missing. I tried another registry browser, and I was able to see the missing tags that do not appear in docker-registry-browser. I also verified this by using the CLI tool docker-ls to list all of my repositories and tags.

At first, I encountered similar problems to this issue. In my case, when I ran docker-registry-browser on a separate host from the registry, I had to use the IP address of the docker registry server to workaround the same DNS problem. Otherwise, the registry browser did not work at all.

![image](https://user-images.githubusercontent.com/12653977/51284061-d3821680-19af-11e9-9000-f54d9f96e7b9.png)

 However, when I ran docker-registry-browser on the registry server itself (using the hostname in the URL), I could browse the registry. It seemed like it was working until I realized I there were some tags missing.

But when I went back to using the IP address in the URL instead of the hostname, then all the tags appeared in the browser.

More info:
I encountered the same DNS error in the container logs: **getaddrinfo: Name does not resolve**

I started a shell inside the container and installed the bind-tools package. I was able to resolve the registry hostname via nslookup, but ping would say **bad address**. But, I could ping the registry if I used its IP address instead of the hostname.

**Comment by jmmen1** [comment] 2019-01-22 16:13
The registry server is a linux vm running in my work's internal corporate network. I am connecting to the server from my corporate laptop via its FQDN, not a .local address.

The tags simply did not appear in the list. This was confirmed by another developer. He was working with some images, and he retagged some of his images locally, then pushed the new tags, but neither the old nor the new tags appeared in the list. It was if they did not exist at all.

I did notice that the majority of the tags that were missing were tags that contained numbers. For example, we have several tomcat images, and the image tagged "dev" appeared in the list, but the image tagged with just the version number, "7.0.53" did not appear in the list. Then, the developer pulled the 7.0.53 image, retagged it with the date, 7.0.53-01152019, then pushed it back to the registry, but that tag did not appear in the registry browser either.

**Comment by klausmeyer** [comment] 2019-01-22 18:49
I tried to reproduce the issue(s) but wasn't able - sorry :(

What I have tried so far:

1. Mac running the application (without docker) talking to a registry container on the same host
2. Mac running the application (with docker) talking to a registry container on the same host
3. Mac running the application (with docker) talking to a registry running on a external Linux machine

For all three cases I used FQDNs provided by the router in my home network to see if I get any DNS issues. I also had a few different example images & tags on the registries to see if I can trigger the missing tags problem:

```
- <registry>/tomcat:dev
- <registry>/tomcat:7.0.53
- <registry>/tomcat:v7.0.53
- <registry>/something/tomcat:dev
- <registry>/something/tomcat:7.0.53
- <registry>/something/tomcat:v7.0.53
```

Maybe you could check and see if the DNS stuff is also not working in a plain `ruby:2.6.0-alpine` container?

Cheers, Klaus

**Comment by jmmen1** [comment] 2019-01-23 17:43
The issue seems to be in the base image.

I installed the bind-tools package in both a ruby:2.6.0-alpine container and an alpine:3.8 container. I encountered the same "bad address" error message when trying to ping a hostname. As before, pinging the IP address works.

**Comment by jmmen1** [comment] 2019-02-05 17:30
It's definitely something with alpine. I ran a while loop in an alpine:edge container to ping the host once every 3 seconds, and the ping succeeded only one in 100 tries.

It never fails if I use an ubuntu container.

**Comment by klausmeyer** [comment] 2019-02-05 18:21
Did you manage to try with the recently released alpine 3.9?

**Comment by jmmen1** [comment] 2019-02-07 17:04
Hmm, I don't know what's changed, but when I try the ping loop now, it works perfectly. When I tried alpine:edge last week, only 1 out of 100 pings worked. Now, all 100 pings were successful, and I tried with alpine 3.6, 3.8, 3.8, and edge.

Maybe our IT department made a change to corporate DNS?

**Comment by jmmen1** [comment] 2019-02-07 17:11
I tried with alpine:edge, and alpine:3.9. If I run a loop of 100 pings, I rarely get a successful ping. Mostly, it's the "bad address" error.

However, if I create a network via "docker network create" and use that network in the "docker run" command, ping works perfectly every time.

**Comment by klausmeyer** [comment] 2019-02-07 17:50
Ok thanks for testing.
I was just thinking that maybe they changed something in the new release which "fixed" your issue.

However since this seems to be an issue that only pops up in some special cases and also in the raw alpine image without my application I'd close this issue again.

What about the missing tags you mentioned - is this still a problem?

**Comment by jmmen1** [comment] 2019-02-07 19:11
I think the missing tags were related to the DNS issues. When I used the IP address in the URL, I can see all of the tags.

**Comment by klausmeyer** [comment] 2019-02-08 06:25
Ok 👍

**Closed by klausmeyer** 2019-02-08 06:25 UTC
Labels: question

**Comment by dcr26** [comment] 2019-03-12 08:21
hi guys - ive had the same problem. I had my registry resolved as registry.gecko-is.co.uk:5000:[IP] but the registry browser could not resolve this. To fix it, i made sure the registry-browser was on the same overlay network, and used the docker-registry's internal ip address [10.x.x.x]:5000 as docker-registry-browser DOCKER_REGISTRY_URL param. Hope this helps someone else.
