### ISSUE TITLE
Delete throws 404

### ISSUE THREAD

**Issue by c0nd3mn3d** [klausmeyer/docker-registry-browser#15] opened 2017-11-14 08:01 UTC
Huhu,

if I try to deleta a Tag a 404 is shown and the log shows:
```
registry-browser_1  | I, [2017-11-14T07:43:36.237549 #6]  INFO -- : [60085b92-41b8-4f6c-a10e-9189bebd4fd4] Started DELETE "/repo/xx/yy-zz/tag/latest" for xxx.xxx.xxx.xxx at 2017-11-14 07:43:36 +0000
registry-browser_1  | F, [2017-11-14T07:43:36.238675 #6] FATAL -- : [60085b92-41b8-4f6c-a10e-9189bebd4fd4]
registry-browser_1  | F, [2017-11-14T07:43:36.238786 #6] FATAL -- : [60085b92-41b8-4f6c-a10e-9189bebd4fd4] ActionController::RoutingError (No route matches [DELETE] "/repo/xx/yy-zz/tag/latest"):
registry-browser_1  | F, [2017-11-14T07:43:36.238860 #6] FATAL -- : [60085b92-41b8-4f6c-a10e-9189bebd4fd4]
registry-browser_1  | F, [2017-11-14T07:43:36.238982 #6] FATAL -- : [60085b92-41b8-4f6c-a10e-9189bebd4fd4] actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
```

Do you have any idea what I am doing wrong?

Best regards

**Comment by klausmeyer** [comment] 2017-11-14 08:51
Hi @c0nd3mn3d,

you're not doing anything wrong here 😀

There is an actual bug in the delete button's functionality in the current version.
I've pushed a fix for this and an updated docker image should be available soon.

Cheers, Klaus

**Comment by klausmeyer** [comment] 2017-11-14 09:03
```
Successfully built 6b45cf067cd0
Successfully tagged klausmeyer/docker-registry-browser:latest
Pushing index.docker.io/klausmeyer/docker-registry-browser:latest...
Done!
Build finished
```

Can you please pull this new image and check if the problem is solved for you?

**Comment by c0nd3mn3d** [comment] 2017-11-14 14:18
Hi Klaus and thanks for the fast answer.

Now we have:
```
I, [2017-11-14T14:16:11.592238 #7]  INFO -- : [5fb43c30-e8d9-490f-bd6d-d124828b0330] Completed 500 Internal Server Error in 19ms
F, [2017-11-14T14:16:11.593197 #7] FATAL -- : [5fb43c30-e8d9-490f-bd6d-d124828b0330]
F, [2017-11-14T14:16:11.593288 #7] FATAL -- : [5fb43c30-e8d9-490f-bd6d-d124828b0330] Faraday::ClientError (the server responded with status 405):
F, [2017-11-14T14:16:11.593377 #7] FATAL -- : [5fb43c30-e8d9-490f-bd6d-d124828b0330]
F, [2017-11-14T14:16:11.593473 #7] FATAL -- : [5fb43c30-e8d9-490f-bd6d-d124828b0330] app/models/tag.rb:37:in `delete'
```

Best regards,
Tristan

**Comment by c0nd3mn3d** [comment] 2017-11-14 14:25
Ah, sorry... now it has been my fault: I had a typo in my environment settings.

Works like a charm, now. Thanks again.

Best regards,
Tristan

**Comment by klausmeyer** [comment] 2017-11-14 14:30
Cool 👍

**Closed by klausmeyer** 2017-11-14 14:30 UTC
Labels: bug

**Comment by DylanGraham** [comment] 2018-04-12 01:32
@c0nd3mn3d I have the same 405 error, can you please show your environment? Thank you.

**Comment by c0nd3mn3d** [comment] 2018-05-31 07:18
@DylanGraham Sorry, I have been off for a while. If you still need it:

`"Env": [
                "BASIC_AUTH_PASSWORD=password",
                "DOCKER_REGISTRY_URL=http://registry:5000",
                "BASIC_AUTH_USER=user",
                "PUBLIC_REGISTRY_URL=registry.host.tld",
                "ENABLE_DELETE_IMAGES=true",
                "PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "RUBY_MAJOR=2.4",
                "RUBY_VERSION=2.4.2",
                "RUBY_DOWNLOAD_SHA256=748a8980d30141bd1a4124e11745bb105b436fb1890826e0d2b9ea31af27f735",
                "RUBYGEMS_VERSION=2.7.2",
                "BUNDLER_VERSION=1.16.0",
                "GEM_HOME=/usr/local/bundle",
                "BUNDLE_PATH=/usr/local/bundle",
                "BUNDLE_BIN=/usr/local/bundle/bin",
                "BUNDLE_SILENCE_ROOT_WARNING=1",
                "BUNDLE_APP_CONFIG=/usr/local/bundle",
                "PORT=8080",
                "RAILS_ENV=production",
                "SECRET_KEY_BASE=changeme",
                "RAILS_SERVE_STATIC_FILES=true",
                "RAILS_LOG_TO_STDOUT=true"
            ],`
